variables:
  COMPONENT_IMAGE: registry.moetz.dev/buzzer:$CI_BUILD_REF_NAME
  COMPONENT_BRANCH_IMAGE: registry.moetz.dev/buzzer:$CI_COMMIT_REF_NAME
  COMPONENT_LATEST_IMAGE: registry.moetz.dev/buzzer:latest

stages:
  - build_application
  - build_image
  - tag_image


build application:
  stage: build_application
  script:
    - ./gradlew clean build shadowJar
  artifacts:
    paths:
      - build/libs/Buzzer.jar
  tags:
    - maven

build and push:
  stage: build_image
  script:
    - echo $COMPONENT_IMAGE
    - docker build --pull -t $COMPONENT_IMAGE ./
    - docker login -u $REGISTRY_MOETZ_DEV_USERNAME -p $REGISTRY_MOETZ_DEV_PASSWORD registry.moetz.dev
    - docker push $COMPONENT_IMAGE
  tags:
    - docker
  only:
    - develop
    - master
    - tags

tag latest:
  stage: tag_image
  script:
    - docker login -u $REGISTRY_MOETZ_DEV_USERNAME -p $REGISTRY_MOETZ_DEV_PASSWORD registry.moetz.dev
    - docker pull $COMPONENT_IMAGE
    - docker tag $COMPONENT_IMAGE $COMPONENT_LATEST_IMAGE
    - docker push $COMPONENT_LATEST_IMAGE
  tags:
    - docker
  only:
    - master

tag branch name:
  stage: tag_image
  script:
    - docker login -u $REGISTRY_MOETZ_DEV_USERNAME -p $REGISTRY_MOETZ_DEV_PASSWORD registry.moetz.dev
    - docker pull $COMPONENT_IMAGE
    - docker tag $COMPONENT_IMAGE $COMPONENT_BRANCH_IMAGE
    - docker push $COMPONENT_BRANCH_IMAGE
  tags:
    - docker
